# rag_evaluation/config.yml

source_document_path: "./data" 
qa_dataset_path: "./data/qa.csv"

server:
  base_url: "http://localhost:8000"
  create_empty_vs_endpoint: "/v1/rag/vs/empty"
  add_document_endpoint: "/v1/rag/vs/{vs_id}/documents"
  ask_endpoint: "/v1/rag/vs/{vs_id}/chat"
  delete_vs_endpoint: "/v1/rag/vs/{vs_id}"

ragas:
  llm_model: "gemma3:4b" 
  embedding_model: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
  ollama_base_url: "http://services.aiopt.io:11434"